#coding=utf-8

def Naive(T, W):
    i, j = 0, 0
    pos = []
    while i < len(T) and j < len(W):
        if T[i] == W[j]:
            j += 1
            if j == len(W):
                head = i - j + 1
                pos.append(head)
                j = 0
        else:
            i -= j
            j = 0

        i += 1

    return pos

def KnuthMorrisPratt(T, W):
    pos = []
    # create table
    P = [-1,]
    for i in range(1,len(W)):
        suffix_set = [ W[i-j:i] for j in range(1,i) ]
        #print i,suffix_set
        max_match = 0
        for suffix in suffix_set:
            matched = 0
            for k,x in enumerate(suffix):
                if x != W[k]:
                    break
                else:
                    matched = k+1
            if matched > max_match: max_match = matched
        P.append(max_match)

    # search
    i, m = 0, 0
    while m + i < len(T):
        if W[i] == T[m + i]:
            i += 1
            if i == len(W):
                pos.append(m)
                i = 0
                m += 1
        else:
            m += i - P[i]
            if i > 0:
                i = P[i]
    return pos

T = u"""aaaabsdajsbddsshdaabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksdueabsdajsbddsshdaabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksdueabsdajsbddsshdaabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksdueabsdajsbddsshdaabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksdueabsdajsbddsshdaabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebsdajsbddsshdaabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfhdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayaabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsayabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsaydgakdvalidfagslakhabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsaydgakdvalidfagslakhabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsaydgakdvalidfagslakhabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsaydgakdvalidfagslakhabsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsaydgakdvalidfagslakhbsdajsbdshdabcdabdabfaksduebaubruaabcdabdbasygavksbkajsdakhgfasvdbvansbvanbavsnbavdkjashblkfagsaydgakdvalidfagslakh"""

print Naive(T, u"abcdabd")
print KnuthMorrisPratt(T, u"abcdabd")

#print KnuthMorrisPratt(T, u"Knuth")
#print KnuthMorrisPratt(T, u"Pratt")
#print KnuthMorrisPratt(T, u"アルゴリズム")
